SPK_NAME = povray
SPK_VERS = 3.7.0.8
SPK_REV = 2
SPK_ICON = src/povray.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = DigitalBox
DESCRIPTION = The Persistence of Vision Raytracer is a high-quality, Free Software tool for creating stunning three-dimensional graphics.

RELOAD_UI = no
STARTABLE = no
DISPLAY_NAME = Povray

HOMEPAGE   = https://www.povray.org
LICENSE    = AGPLv3

SPK_COMMANDS = bin/povray
SPK_USR_LOCAL_LINKS  = bin:bin/povray

include ../../mk/spksrc.spk.mk

