SPK_NAME = imagemagick
SPK_VERS = 7.0.10
SPK_REV = 5
SPK_ICON = src/imagemagick.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = DigitalBox
DESCRIPTION = ImageMagick is a software suite to create, edit, compose, or convert bitmap images.
DISPLAY_NAME = ImageMagick
CHANGELOG = Update to ImageMagick 7.0.10-61

STARTABLE = no

HOMEPAGE = https://www.imagemagick.org/
LICENSE  = Apache 2.0

include ../../mk/spksrc.spk.mk
