SPK_NAME = erlang
SPK_VERS = 23.2.5
SPK_REV = 2
SPK_ICON = src/erlang.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = DigitalBox
DESCRIPTION = Erlang is a programming language used to build massively scalable soft real-time systems with requirements on high availability. Some of its uses are in telecoms, banking, e-commerce, computer telephony and instant messaging. Erlang's runtime system has built-in support for concurrency, distribution and fault tolerance.
RELOAD_UI = no
STARTABLE = no
DISPLAY_NAME = Erlang

HOMEPAGE   = http://www.erlang.org
LICENSE    = Apache 2.0

SPK_COMMANDS = bin/erl bin/erlc
SPK_USR_LOCAL_LINKS  = bin:bin/erlc bin:bin/erl

include ../../mk/spksrc.spk.mk

