PKG_NAME = dkb-trace
PKG_VERS = 2.2
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS)-dsm7.$(PKG_EXT)
#PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://digital.box.free.fr/sources
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://digital.box.free.fr/
COMMENT  = DKB Trace RayTracer
LICENSE  = GPLv2

GNU_CONFIGURE = 1

CONFIGURE_ARGS = 

include ../../mk/spksrc.cross-cc.mk

