SPK_NAME = sqlite
SPK_VERS = 3.30.1
SPK_REV = 1
SPK_ICON = src/sqlite3.png
DSM_UI_DIR = app

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = DigitalBox
DESCRIPTION = SQLite is a C-language library that implements a small, fast, self-contained, high-reliability, full-featured, SQL database engine.

RELOAD_UI = yes
STARTABLE = no
DISPLAY_NAME = sqlite

HOMEPAGE = http://www.sqlite.org
LICENSE  = GPL

INSTALLER_SCRIPT = src/installer.sh

include ../../mk/spksrc.spk.mk

