SPK_NAME = mpd
SPK_VERS = 0.20.23
SPK_REV = 1
SPK_ICON = src/mpd.png
DSM_UI_DIR = app

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = DigitalBox
DESCRIPTION = 

RELOAD_UI = yes
STARTABLE = yes
DISPLAY_NAME = MPD

HOMEPAGE   = https://www.musicpd.org/
LICENSE    = GPLv2

include ../../mk/spksrc.spk.mk

