SPK_NAME = ezstream
SPK_VERS = 1.0.1
SPK_REV = 2
SPK_ICON = src/ezstream.png

DEPENDS  = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = EZStream is a command line source client for Icecast media streaming server 

DISPLAY_NAME = ezstream

HOMEPAGE   = http://www.icecast.org/
LICENSE    = GPLv2

STARTABLE = no

include ../../mk/spksrc.spk.mk
